model:
  name: latent_mapping

task:
  name: latent_mapping
  max_steps: 5_000
  train_dl:
    batch_size: 16

optimizer:
  name: adam
  lr: 3e-4

lr_scheduler:
  name: linear

trainer:
  name: sl

logger:
  - name: stdout
  - name: tensorboard

launcher:
  name: mp
